site_name: Ultimaille


theme:
    name: material
    language: en
    logo: assets/logo.png
    palette:
        primary: teal
        
markdown_extensions:
    - pymdownx.arithmatex:
        generic: true
    - admonition
    - pymdownx.details
    - pymdownx.superfences

extra_javascript:
    - javascripts/mathjax.js
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


extra:
  alternate:
    -name: English
    link: /en/
    lang: en
    -name: Français
    link: /fr/
    lang: fr

repo_url: https://github.com/ultimaille/ultimaille

plugins:
  - include-markdown